services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        volumes:
            - '.:/var/www/html'
        depends_on:
            - mysql
       
            
    mysql:
        image: "mysql:8.0"
        ports:
            - "${DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mysql-data:/var/lib/mysql
        # healthcheck:
        #     test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
        #     timeout: 5s
        #     retries: 3
    phpmyadmin:
        image: "phpmyadmin:5.2.1"
        ports:
            - "${APP_PORT:-81}:81"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: password
        depends_on:
            - mysql

    

volumes:
  mysql-data:
    driver: local
