services:
  
  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    env_file:
      - .env
    environment:
      - DB_HOST=mysql_db
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=root
    depends_on:
      mysql_db:
        condition: service_healthy

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      mysql_db:
        condition: service_healthy

volumes:
  mysql_data: