services:

  # Monitoring with watchtower
  jcoatching-watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
      - "--cleanup"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jcoaching-network


  # Laravel app container
  jcoaching-app:
    image: hakimfidjel/jcoaching:latest
    volumes:
      - .env:/var/www/html/.env 
    entrypoint: /usr/local/bin/entrypoint-app.sh
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      - "traefik.http.routers.app.rule=Host(`jcoaching.fr`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - jcoaching-mysql
    restart: always
    networks:
      - jcoaching-network
      - traefik-network
    # deploy:
    #   mode: replicated
    #   replicas: 2

  # MySQL database container
  jcoaching-mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql 
      - .env:/run/secrets/.env  
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} 
      MYSQL_DATABASE: ${DB_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always
    networks:
      - jcoaching-network

  # PhpMyAdmin container
  jcoaching-phpmyadmin:
    image: phpmyadmin:5.2.1
    volumes:
      - .env:/var/www/html/.env 
    environment:
      - PMA_ARBITRARY=1
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.jcoaching.fr`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=myresolver"
    depends_on:
      - jcoaching-mysql
    restart: always
    networks:
      - jcoaching-network
      - traefik-network

  # Laravel Reverb container
  jcoaching-reverb:
    image: hakimfidjel/jcoaching:latest
    volumes:
      - .env:/var/www/html/.env 
    entrypoint: /usr/local/bin/entrypoint-reverb.sh
    # expose:
    #   - "8080"
    # ports:
    #   - "8080:8080"  # Ajouter cette ligne
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      - "traefik.http.routers.reverb.rule=Host(`websocket.jcoaching.fr`)"
      - "traefik.http.routers.reverb.entrypoints=websecure"
      - "traefik.http.routers.reverb.tls.certresolver=myresolver"
      - "traefik.http.routers.reverb.tls=true"
      - "traefik.http.services.reverb.loadbalancer.server.port=8080"
      - "traefik.http.services.reverb.loadbalancer.server.scheme=http"
    depends_on:
      jcoaching-mysql:
        condition: service_healthy
    restart: always
    networks:
      - jcoaching-network
      - traefik-network


networks:
  jcoaching-network:
    driver: bridge
  traefik-network:
    external: true

volumes:
  mysql_data:
